/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "unity.h"
#include "pll.h"
#include "arm_math.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_edge_1p_zero_input_theta_stays_valid(void);
extern void test_edge_3p_zero_input_theta_stays_valid(void);
extern void test_edge_1p_zero_input_clears_lock(void);
extern void test_edge_3p_zero_input_clears_lock(void);
extern void test_edge_1p_large_amplitude_theta_valid(void);
extern void test_edge_3p_large_amplitude_theta_valid(void);
extern void test_edge_3p_amplitude_drop_stays_locked(void);
extern void test_edge_1p_signal_loss_and_recovery(void);
extern void test_edge_3p_signal_loss_and_recovery(void);
extern void test_edge_3p_phase_jump_180_recovers(void);
extern void test_edge_1p_phase_jump_180_recovers(void);
extern void test_edge_3p_locks_at_45Hz(void);
extern void test_edge_3p_locks_at_65Hz(void);
extern void test_edge_update_fs_arr_clamped_at_50Hz(void);
extern void test_edge_update_fs_clamps_below_45Hz(void);
extern void test_edge_update_fs_clamps_above_65Hz(void);
extern void test_edge_1p_single_update_after_init(void);
extern void test_edge_3p_single_update_after_init(void);
extern void test_edge_1p_reinit_while_running_resets_state(void);
extern void test_edge_3p_reinit_while_running_resets_state(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
 int main(int argc, char** argv)
{
#ifdef UNITY_USE_COMMAND_LINE_ARGS
  int parse_status = UnityParseOptions(argc, argv);
  if (parse_status != 0)
  {
    if (parse_status < 0)
    {
      UnityPrint("test_pll_edge.");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_1p_zero_input_theta_stays_valid");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_3p_zero_input_theta_stays_valid");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_1p_zero_input_clears_lock");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_3p_zero_input_clears_lock");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_1p_large_amplitude_theta_valid");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_3p_large_amplitude_theta_valid");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_3p_amplitude_drop_stays_locked");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_1p_signal_loss_and_recovery");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_3p_signal_loss_and_recovery");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_3p_phase_jump_180_recovers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_1p_phase_jump_180_recovers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_3p_locks_at_45Hz");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_3p_locks_at_65Hz");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_update_fs_arr_clamped_at_50Hz");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_update_fs_clamps_below_45Hz");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_update_fs_clamps_above_65Hz");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_1p_single_update_after_init");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_3p_single_update_after_init");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_1p_reinit_while_running_resets_state");
      UNITY_PRINT_EOL();
      UnityPrint("  test_edge_3p_reinit_while_running_resets_state");
      UNITY_PRINT_EOL();
      return 0;
    }
    return parse_status;
  }
#endif
  UnityBegin("test_pll_edge.c");
  run_test(test_edge_1p_zero_input_theta_stays_valid, "test_edge_1p_zero_input_theta_stays_valid", 95);
  run_test(test_edge_3p_zero_input_theta_stays_valid, "test_edge_3p_zero_input_theta_stays_valid", 108);
  run_test(test_edge_1p_zero_input_clears_lock, "test_edge_1p_zero_input_clears_lock", 124);
  run_test(test_edge_3p_zero_input_clears_lock, "test_edge_3p_zero_input_clears_lock", 142);
  run_test(test_edge_1p_large_amplitude_theta_valid, "test_edge_1p_large_amplitude_theta_valid", 170);
  run_test(test_edge_3p_large_amplitude_theta_valid, "test_edge_3p_large_amplitude_theta_valid", 186);
  run_test(test_edge_3p_amplitude_drop_stays_locked, "test_edge_3p_amplitude_drop_stays_locked", 209);
  run_test(test_edge_1p_signal_loss_and_recovery, "test_edge_1p_signal_loss_and_recovery", 239);
  run_test(test_edge_3p_signal_loss_and_recovery, "test_edge_3p_signal_loss_and_recovery", 272);
  run_test(test_edge_3p_phase_jump_180_recovers, "test_edge_3p_phase_jump_180_recovers", 299);
  run_test(test_edge_1p_phase_jump_180_recovers, "test_edge_1p_phase_jump_180_recovers", 321);
  run_test(test_edge_3p_locks_at_45Hz, "test_edge_3p_locks_at_45Hz", 344);
  run_test(test_edge_3p_locks_at_65Hz, "test_edge_3p_locks_at_65Hz", 363);
  run_test(test_edge_update_fs_arr_clamped_at_50Hz, "test_edge_update_fs_arr_clamped_at_50Hz", 389);
  run_test(test_edge_update_fs_clamps_below_45Hz, "test_edge_update_fs_clamps_below_45Hz", 410);
  run_test(test_edge_update_fs_clamps_above_65Hz, "test_edge_update_fs_clamps_above_65Hz", 425);
  run_test(test_edge_1p_single_update_after_init, "test_edge_1p_single_update_after_init", 444);
  run_test(test_edge_3p_single_update_after_init, "test_edge_3p_single_update_after_init", 455);
  run_test(test_edge_1p_reinit_while_running_resets_state, "test_edge_1p_reinit_while_running_resets_state", 473);
  run_test(test_edge_3p_reinit_while_running_resets_state, "test_edge_3p_reinit_while_running_resets_state", 489);

  return UNITY_END();
}
