/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "unity.h"
#include "ema.h"
#include "maf.h"
#include "share_data.h"
#include "share_types.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_ema_basic_formula(void);
extern void test_ema_alpha_1_returns_input(void);
extern void test_ema_alpha_0_returns_last(void);
extern void test_ema_converges_to_constant_input(void);
extern void test_ema_step_response_monotonic(void);
extern void test_ema_negative_input(void);
extern void test_ema_zero_input_zero_last(void);
extern void test_maf_init_clears_state(void);
extern void test_maf_single_sample_returns_itself_divided_by_size(void);
extern void test_maf_converges_to_constant(void);
extern void test_maf_output_is_running_average(void);
extern void test_maf_circular_buffer_wraps(void);
extern void test_maf_sample_count_wraps_at_max(void);
extern void test_maf_zero_input_returns_zero(void);
extern void test_maf_negative_samples(void);
extern void test_shdat_initial_state_is_start(void);
extern void test_shdat_set_and_get_state(void);
extern void test_shdat_all_states_settable(void);
extern void test_shdat_wrt_and_get_frequency(void);
extern void test_shdat_wrt_and_get_rms_voltage(void);
extern void test_shdat_wrt_and_get_active_power(void);
extern void test_shdat_double_buffer_swap(void);
extern void test_shdat_ema_smoothing_single_step(void);
extern void test_shdat_energy_passthrough(void);
extern void test_shdat_vol_line_ema_smoothed(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
 int main(int argc, char** argv)
{
#ifdef UNITY_USE_COMMAND_LINE_ARGS
  int parse_status = UnityParseOptions(argc, argv);
  if (parse_status != 0)
  {
    if (parse_status < 0)
    {
      UnityPrint("test_ema_maf_shdat.");
      UNITY_PRINT_EOL();
      UnityPrint("  test_ema_basic_formula");
      UNITY_PRINT_EOL();
      UnityPrint("  test_ema_alpha_1_returns_input");
      UNITY_PRINT_EOL();
      UnityPrint("  test_ema_alpha_0_returns_last");
      UNITY_PRINT_EOL();
      UnityPrint("  test_ema_converges_to_constant_input");
      UNITY_PRINT_EOL();
      UnityPrint("  test_ema_step_response_monotonic");
      UNITY_PRINT_EOL();
      UnityPrint("  test_ema_negative_input");
      UNITY_PRINT_EOL();
      UnityPrint("  test_ema_zero_input_zero_last");
      UNITY_PRINT_EOL();
      UnityPrint("  test_maf_init_clears_state");
      UNITY_PRINT_EOL();
      UnityPrint("  test_maf_single_sample_returns_itself_divided_by_size");
      UNITY_PRINT_EOL();
      UnityPrint("  test_maf_converges_to_constant");
      UNITY_PRINT_EOL();
      UnityPrint("  test_maf_output_is_running_average");
      UNITY_PRINT_EOL();
      UnityPrint("  test_maf_circular_buffer_wraps");
      UNITY_PRINT_EOL();
      UnityPrint("  test_maf_sample_count_wraps_at_max");
      UNITY_PRINT_EOL();
      UnityPrint("  test_maf_zero_input_returns_zero");
      UNITY_PRINT_EOL();
      UnityPrint("  test_maf_negative_samples");
      UNITY_PRINT_EOL();
      UnityPrint("  test_shdat_initial_state_is_start");
      UNITY_PRINT_EOL();
      UnityPrint("  test_shdat_set_and_get_state");
      UNITY_PRINT_EOL();
      UnityPrint("  test_shdat_all_states_settable");
      UNITY_PRINT_EOL();
      UnityPrint("  test_shdat_wrt_and_get_frequency");
      UNITY_PRINT_EOL();
      UnityPrint("  test_shdat_wrt_and_get_rms_voltage");
      UNITY_PRINT_EOL();
      UnityPrint("  test_shdat_wrt_and_get_active_power");
      UNITY_PRINT_EOL();
      UnityPrint("  test_shdat_double_buffer_swap");
      UNITY_PRINT_EOL();
      UnityPrint("  test_shdat_ema_smoothing_single_step");
      UNITY_PRINT_EOL();
      UnityPrint("  test_shdat_energy_passthrough");
      UNITY_PRINT_EOL();
      UnityPrint("  test_shdat_vol_line_ema_smoothed");
      UNITY_PRINT_EOL();
      return 0;
    }
    return parse_status;
  }
#endif
  UnityBegin("test_ema_maf_shdat.c");
  run_test(test_ema_basic_formula, "test_ema_basic_formula", 58);
  run_test(test_ema_alpha_1_returns_input, "test_ema_alpha_1_returns_input", 64);
  run_test(test_ema_alpha_0_returns_last, "test_ema_alpha_0_returns_last", 70);
  run_test(test_ema_converges_to_constant_input, "test_ema_converges_to_constant_input", 76);
  run_test(test_ema_step_response_monotonic, "test_ema_step_response_monotonic", 85);
  run_test(test_ema_negative_input, "test_ema_negative_input", 96);
  run_test(test_ema_zero_input_zero_last, "test_ema_zero_input_zero_last", 102);
  run_test(test_maf_init_clears_state, "test_maf_init_clears_state", 111);
  run_test(test_maf_single_sample_returns_itself_divided_by_size, "test_maf_single_sample_returns_itself_divided_by_size", 121);
  run_test(test_maf_converges_to_constant, "test_maf_converges_to_constant", 130);
  run_test(test_maf_output_is_running_average, "test_maf_output_is_running_average", 141);
  run_test(test_maf_circular_buffer_wraps, "test_maf_circular_buffer_wraps", 153);
  run_test(test_maf_sample_count_wraps_at_max, "test_maf_sample_count_wraps_at_max", 167);
  run_test(test_maf_zero_input_returns_zero, "test_maf_zero_input_returns_zero", 177);
  run_test(test_maf_negative_samples, "test_maf_negative_samples", 187);
  run_test(test_shdat_initial_state_is_start, "test_shdat_initial_state_is_start", 212);
  run_test(test_shdat_set_and_get_state, "test_shdat_set_and_get_state", 218);
  run_test(test_shdat_all_states_settable, "test_shdat_all_states_settable", 226);
  run_test(test_shdat_wrt_and_get_frequency, "test_shdat_wrt_and_get_frequency", 245);
  run_test(test_shdat_wrt_and_get_rms_voltage, "test_shdat_wrt_and_get_rms_voltage", 256);
  run_test(test_shdat_wrt_and_get_active_power, "test_shdat_wrt_and_get_active_power", 267);
  run_test(test_shdat_double_buffer_swap, "test_shdat_double_buffer_swap", 281);
  run_test(test_shdat_ema_smoothing_single_step, "test_shdat_ema_smoothing_single_step", 303);
  run_test(test_shdat_energy_passthrough, "test_shdat_energy_passthrough", 326);
  run_test(test_shdat_vol_line_ema_smoothed, "test_shdat_vol_line_ema_smoothed", 341);

  return UNITY_END();
}
