/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "unity.h"
#include "meter_register.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_mreg_get_data_returns_non_null(void);
extern void test_mreg_get_data_matches_last_written(void);
extern void test_mreg_voltage_phase_registers(void);
extern void test_mreg_voltage_line_registers(void);
extern void test_mreg_current_phase_registers(void);
extern void test_mreg_neutral_current_is_sum(void);
extern void test_mreg_active_power_phase_registers(void);
extern void test_mreg_active_power_total_is_sum(void);
extern void test_mreg_reactive_power_phase_registers(void);
extern void test_mreg_reactive_power_total_is_sum(void);
extern void test_mreg_apparent_power_phase_registers(void);
extern void test_mreg_apparent_power_total_is_sum(void);
extern void test_mreg_power_factor_phase_registers(void);
extern void test_mreg_power_factor_total_is_sum(void);
extern void test_mreg_frequency_register(void);
extern void test_mreg_frequency_boundary_45Hz(void);
extern void test_mreg_frequency_boundary_65Hz(void);
extern void test_mreg_energy_export_kwh_conversion(void);
extern void test_mreg_energy_import_is_zero(void);
extern void test_mreg_energy_reactive_not_implemented(void);
extern void test_mreg_thd_voltage_registers(void);
extern void test_mreg_thd_current_registers(void);
extern void test_mreg_snapshot_all_fields_preserved(void);
extern void test_mreg_overwrite_updates_registers(void);
extern void test_mreg_overwrite_updates_snapshot(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
 int main(int argc, char** argv)
{
#ifdef UNITY_USE_COMMAND_LINE_ARGS
  int parse_status = UnityParseOptions(argc, argv);
  if (parse_status != 0)
  {
    if (parse_status < 0)
    {
      UnityPrint("test_meter_register.");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_get_data_returns_non_null");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_get_data_matches_last_written");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_voltage_phase_registers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_voltage_line_registers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_current_phase_registers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_neutral_current_is_sum");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_active_power_phase_registers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_active_power_total_is_sum");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_reactive_power_phase_registers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_reactive_power_total_is_sum");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_apparent_power_phase_registers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_apparent_power_total_is_sum");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_power_factor_phase_registers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_power_factor_total_is_sum");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_frequency_register");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_frequency_boundary_45Hz");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_frequency_boundary_65Hz");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_energy_export_kwh_conversion");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_energy_import_is_zero");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_energy_reactive_not_implemented");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_thd_voltage_registers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_thd_current_registers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_snapshot_all_fields_preserved");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_overwrite_updates_registers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mreg_overwrite_updates_snapshot");
      UNITY_PRINT_EOL();
      return 0;
    }
    return parse_status;
  }
#endif
  UnityBegin("test_meter_register.c");
  run_test(test_mreg_get_data_returns_non_null, "test_mreg_get_data_returns_non_null", 136);
  run_test(test_mreg_get_data_matches_last_written, "test_mreg_get_data_matches_last_written", 143);
  run_test(test_mreg_voltage_phase_registers, "test_mreg_voltage_phase_registers", 157);
  run_test(test_mreg_voltage_line_registers, "test_mreg_voltage_line_registers", 166);
  run_test(test_mreg_current_phase_registers, "test_mreg_current_phase_registers", 179);
  run_test(test_mreg_neutral_current_is_sum, "test_mreg_neutral_current_is_sum", 188);
  run_test(test_mreg_active_power_phase_registers, "test_mreg_active_power_phase_registers", 202);
  run_test(test_mreg_active_power_total_is_sum, "test_mreg_active_power_total_is_sum", 211);
  run_test(test_mreg_reactive_power_phase_registers, "test_mreg_reactive_power_phase_registers", 225);
  run_test(test_mreg_reactive_power_total_is_sum, "test_mreg_reactive_power_total_is_sum", 234);
  run_test(test_mreg_apparent_power_phase_registers, "test_mreg_apparent_power_phase_registers", 248);
  run_test(test_mreg_apparent_power_total_is_sum, "test_mreg_apparent_power_total_is_sum", 257);
  run_test(test_mreg_power_factor_phase_registers, "test_mreg_power_factor_phase_registers", 271);
  run_test(test_mreg_power_factor_total_is_sum, "test_mreg_power_factor_total_is_sum", 280);
  run_test(test_mreg_frequency_register, "test_mreg_frequency_register", 294);
  run_test(test_mreg_frequency_boundary_45Hz, "test_mreg_frequency_boundary_45Hz", 301);
  run_test(test_mreg_frequency_boundary_65Hz, "test_mreg_frequency_boundary_65Hz", 309);
  run_test(test_mreg_energy_export_kwh_conversion, "test_mreg_energy_export_kwh_conversion", 321);
  run_test(test_mreg_energy_import_is_zero, "test_mreg_energy_import_is_zero", 329);
  run_test(test_mreg_energy_reactive_not_implemented, "test_mreg_energy_reactive_not_implemented", 336);
  run_test(test_mreg_thd_voltage_registers, "test_mreg_thd_voltage_registers", 348);
  run_test(test_mreg_thd_current_registers, "test_mreg_thd_current_registers", 357);
  run_test(test_mreg_snapshot_all_fields_preserved, "test_mreg_snapshot_all_fields_preserved", 370);
  run_test(test_mreg_overwrite_updates_registers, "test_mreg_overwrite_updates_registers", 400);
  run_test(test_mreg_overwrite_updates_snapshot, "test_mreg_overwrite_updates_snapshot", 414);

  return UNITY_END();
}
