/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "mock_hw_stub.h"
#include "unity.h"
#include "mock.h"
#include "arm_math.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_mock_sin_gen_output_within_adc_range(void);
extern void test_mock_sin_gen_dc_offset_near_midpoint(void);
extern void test_mock_sin_gen_jump_space_skips_indices(void);
extern void test_mock_sin_gen_phase_shift_180_inverts_wave(void);
extern void test_mock_sin_gen_peak_amplitude_correct(void);
extern void test_mock_sin_gen_trough_amplitude_correct(void);
extern void test_mock_sin_gen_different_frequencies_differ(void);
extern void test_mock_3p_all_samples_within_adc_range(void);
extern void test_mock_3p_dc_offset_all_channels(void);
extern void test_mock_3p_voltage_phases_120_apart(void);
extern void test_mock_3p_current_phase_shift_applied(void);
extern void test_mock_3p_zero_length_no_crash(void);
extern void test_mock_DMA_init_registers_buffer(void);
extern void test_mock_timer_update_arr_no_crash(void);
extern void test_mock_timer_update_arr_changes_internal_fs(void);
extern void test_mock_change_frequency_no_crash(void);
extern void test_mock_change_frequency_zero_step(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
 int main(int argc, char** argv)
{
#ifdef UNITY_USE_COMMAND_LINE_ARGS
  int parse_status = UnityParseOptions(argc, argv);
  if (parse_status != 0)
  {
    if (parse_status < 0)
    {
      UnityPrint("test_mock.");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_sin_gen_output_within_adc_range");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_sin_gen_dc_offset_near_midpoint");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_sin_gen_jump_space_skips_indices");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_sin_gen_phase_shift_180_inverts_wave");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_sin_gen_peak_amplitude_correct");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_sin_gen_trough_amplitude_correct");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_sin_gen_different_frequencies_differ");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_3p_all_samples_within_adc_range");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_3p_dc_offset_all_channels");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_3p_voltage_phases_120_apart");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_3p_current_phase_shift_applied");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_3p_zero_length_no_crash");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_DMA_init_registers_buffer");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_timer_update_arr_no_crash");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_timer_update_arr_changes_internal_fs");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_change_frequency_no_crash");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mock_change_frequency_zero_step");
      UNITY_PRINT_EOL();
      return 0;
    }
    return parse_status;
  }
#endif
  UnityBegin("test_mock.c");
  run_test(test_mock_sin_gen_output_within_adc_range, "test_mock_sin_gen_output_within_adc_range", 61);
  run_test(test_mock_sin_gen_dc_offset_near_midpoint, "test_mock_sin_gen_dc_offset_near_midpoint", 77);
  run_test(test_mock_sin_gen_jump_space_skips_indices, "test_mock_sin_gen_jump_space_skips_indices", 93);
  run_test(test_mock_sin_gen_phase_shift_180_inverts_wave, "test_mock_sin_gen_phase_shift_180_inverts_wave", 109);
  run_test(test_mock_sin_gen_peak_amplitude_correct, "test_mock_sin_gen_peak_amplitude_correct", 126);
  run_test(test_mock_sin_gen_trough_amplitude_correct, "test_mock_sin_gen_trough_amplitude_correct", 143);
  run_test(test_mock_sin_gen_different_frequencies_differ, "test_mock_sin_gen_different_frequencies_differ", 159);
  run_test(test_mock_3p_all_samples_within_adc_range, "test_mock_3p_all_samples_within_adc_range", 181);
  run_test(test_mock_3p_dc_offset_all_channels, "test_mock_3p_dc_offset_all_channels", 198);
  run_test(test_mock_3p_voltage_phases_120_apart, "test_mock_3p_voltage_phases_120_apart", 218);
  run_test(test_mock_3p_current_phase_shift_applied, "test_mock_3p_current_phase_shift_applied", 250);
  run_test(test_mock_3p_zero_length_no_crash, "test_mock_3p_zero_length_no_crash", 272);
  run_test(test_mock_DMA_init_registers_buffer, "test_mock_DMA_init_registers_buffer", 290);
  run_test(test_mock_timer_update_arr_no_crash, "test_mock_timer_update_arr_no_crash", 324);
  run_test(test_mock_timer_update_arr_changes_internal_fs, "test_mock_timer_update_arr_changes_internal_fs", 337);
  run_test(test_mock_change_frequency_no_crash, "test_mock_change_frequency_no_crash", 357);
  run_test(test_mock_change_frequency_zero_step, "test_mock_change_frequency_zero_step", 366);

  return UNITY_END();
}
