/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "unity.h"
#include "dsp.h"
#include "pll.h"
#include "share_types.h"
#include "arm_math.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_dsp_phase_unity_pf_rms(void);
extern void test_dsp_phase_unity_pf_power(void);
extern void test_dsp_phase_60deg_pf(void);
extern void test_dsp_phase_90deg_zero_active_power(void);
extern void test_dsp_phase_coef_scales_rms(void);
extern void test_dsp_phase_act_pwr_never_exceeds_app_pwr(void);
extern void test_dsp_phase_zero_input(void);
extern void test_dsp_vol_line_balanced_3phase(void);
extern void test_dsp_vol_line_gain_applied(void);
extern void test_dsp_vol_line_zero_input(void);
extern void test_dsp_fre_1p_updates_frequency(void);
extern void test_dsp_fre_3p_updates_frequency(void);
extern void test_dsp_fre_1p_zero_buf_no_crash(void);
extern void test_dsp_thd_pure_sine_near_zero(void);
extern void test_dsp_thd_with_3rd_harmonic(void);
extern void test_dsp_thd_with_3rd_and_5th_harmonic(void);
extern void test_dsp_thd_short_buffer_no_change(void);
extern void test_dsp_thd_angle_cosine_input(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
 int main(int argc, char** argv)
{
#ifdef UNITY_USE_COMMAND_LINE_ARGS
  int parse_status = UnityParseOptions(argc, argv);
  if (parse_status != 0)
  {
    if (parse_status < 0)
    {
      UnityPrint("test_dsp.");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_phase_unity_pf_rms");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_phase_unity_pf_power");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_phase_60deg_pf");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_phase_90deg_zero_active_power");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_phase_coef_scales_rms");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_phase_act_pwr_never_exceeds_app_pwr");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_phase_zero_input");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_vol_line_balanced_3phase");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_vol_line_gain_applied");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_vol_line_zero_input");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_fre_1p_updates_frequency");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_fre_3p_updates_frequency");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_fre_1p_zero_buf_no_crash");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_thd_pure_sine_near_zero");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_thd_with_3rd_harmonic");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_thd_with_3rd_and_5th_harmonic");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_thd_short_buffer_no_change");
      UNITY_PRINT_EOL();
      UnityPrint("  test_dsp_thd_angle_cosine_input");
      UNITY_PRINT_EOL();
      return 0;
    }
    return parse_status;
  }
#endif
  UnityBegin("test_dsp.c");
  run_test(test_dsp_phase_unity_pf_rms, "test_dsp_phase_unity_pf_rms", 99);
  run_test(test_dsp_phase_unity_pf_power, "test_dsp_phase_unity_pf_power", 116);
  run_test(test_dsp_phase_60deg_pf, "test_dsp_phase_60deg_pf", 136);
  run_test(test_dsp_phase_90deg_zero_active_power, "test_dsp_phase_90deg_zero_active_power", 156);
  run_test(test_dsp_phase_coef_scales_rms, "test_dsp_phase_coef_scales_rms", 175);
  run_test(test_dsp_phase_act_pwr_never_exceeds_app_pwr, "test_dsp_phase_act_pwr_never_exceeds_app_pwr", 197);
  run_test(test_dsp_phase_zero_input, "test_dsp_phase_zero_input", 215);
  run_test(test_dsp_vol_line_balanced_3phase, "test_dsp_vol_line_balanced_3phase", 240);
  run_test(test_dsp_vol_line_gain_applied, "test_dsp_vol_line_gain_applied", 266);
  run_test(test_dsp_vol_line_zero_input, "test_dsp_vol_line_zero_input", 295);
  run_test(test_dsp_fre_1p_updates_frequency, "test_dsp_fre_1p_updates_frequency", 321);
  run_test(test_dsp_fre_3p_updates_frequency, "test_dsp_fre_3p_updates_frequency", 338);
  run_test(test_dsp_fre_1p_zero_buf_no_crash, "test_dsp_fre_1p_zero_buf_no_crash", 355);
  run_test(test_dsp_thd_pure_sine_near_zero, "test_dsp_thd_pure_sine_near_zero", 375);
  run_test(test_dsp_thd_with_3rd_harmonic, "test_dsp_thd_with_3rd_harmonic", 396);
  run_test(test_dsp_thd_with_3rd_and_5th_harmonic, "test_dsp_thd_with_3rd_and_5th_harmonic", 423);
  run_test(test_dsp_thd_short_buffer_no_change, "test_dsp_thd_short_buffer_no_change", 449);
  run_test(test_dsp_thd_angle_cosine_input, "test_dsp_thd_angle_cosine_input", 471);

  return UNITY_END();
}
