/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "unity.h"
#include "modbus_rtu.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_crc16_known_vector(void);
extern void test_crc16_single_byte(void);
extern void test_crc16_all_zeros(void);
extern void test_crc16_bit_flip_changes_crc(void);
extern void test_mb_float_roundtrip_50Hz(void);
extern void test_mb_float_roundtrip_negative(void);
extern void test_mb_float_roundtrip_zero(void);
extern void test_mb_float_roundtrip_large(void);
extern void test_mb_float_uses_two_registers(void);
extern void test_mb_float_big_endian_word_order(void);
extern void test_holding_reg_set_and_get(void);
extern void test_holding_reg_boundary_last(void);
extern void test_holding_reg_out_of_bounds_read_returns_zero(void);
extern void test_holding_reg_out_of_bounds_write_no_crash(void);
extern void test_holding_reg_independent_addresses(void);
extern void test_coil_set_true_get_true(void);
extern void test_coil_set_false_get_false(void);
extern void test_coil_adjacent_bits_independent(void);
extern void test_coil_boundary_last(void);
extern void test_coil_out_of_bounds_read_returns_false(void);
extern void test_coil_byte_boundary(void);
extern void test_discrete_input_set_and_get(void);
extern void test_discrete_input_clear(void);
extern void test_discrete_input_out_of_bounds_returns_false(void);
extern void test_input_reg_set_and_get(void);
extern void test_input_reg_boundary_last(void);
extern void test_input_reg_out_of_bounds_returns_zero(void);
extern void test_get_data_store_not_null(void);
extern void test_get_data_store_reflects_set_reg(void);
extern void test_get_data_store_reflects_set_coil(void);
extern void test_fc03_holding_reg_read_via_accessor(void);
extern void test_fc06_write_single_reg_via_accessor(void);
extern void test_fc05_write_single_coil_via_accessor(void);
extern void test_mb_poll_no_frame_no_crash(void);
extern void test_mb_enable_tx_rx_no_crash(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
 int main(int argc, char** argv)
{
#ifdef UNITY_USE_COMMAND_LINE_ARGS
  int parse_status = UnityParseOptions(argc, argv);
  if (parse_status != 0)
  {
    if (parse_status < 0)
    {
      UnityPrint("test_modbus_rtu.");
      UNITY_PRINT_EOL();
      UnityPrint("  test_crc16_known_vector");
      UNITY_PRINT_EOL();
      UnityPrint("  test_crc16_single_byte");
      UNITY_PRINT_EOL();
      UnityPrint("  test_crc16_all_zeros");
      UNITY_PRINT_EOL();
      UnityPrint("  test_crc16_bit_flip_changes_crc");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mb_float_roundtrip_50Hz");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mb_float_roundtrip_negative");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mb_float_roundtrip_zero");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mb_float_roundtrip_large");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mb_float_uses_two_registers");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mb_float_big_endian_word_order");
      UNITY_PRINT_EOL();
      UnityPrint("  test_holding_reg_set_and_get");
      UNITY_PRINT_EOL();
      UnityPrint("  test_holding_reg_boundary_last");
      UNITY_PRINT_EOL();
      UnityPrint("  test_holding_reg_out_of_bounds_read_returns_zero");
      UNITY_PRINT_EOL();
      UnityPrint("  test_holding_reg_out_of_bounds_write_no_crash");
      UNITY_PRINT_EOL();
      UnityPrint("  test_holding_reg_independent_addresses");
      UNITY_PRINT_EOL();
      UnityPrint("  test_coil_set_true_get_true");
      UNITY_PRINT_EOL();
      UnityPrint("  test_coil_set_false_get_false");
      UNITY_PRINT_EOL();
      UnityPrint("  test_coil_adjacent_bits_independent");
      UNITY_PRINT_EOL();
      UnityPrint("  test_coil_boundary_last");
      UNITY_PRINT_EOL();
      UnityPrint("  test_coil_out_of_bounds_read_returns_false");
      UNITY_PRINT_EOL();
      UnityPrint("  test_coil_byte_boundary");
      UNITY_PRINT_EOL();
      UnityPrint("  test_discrete_input_set_and_get");
      UNITY_PRINT_EOL();
      UnityPrint("  test_discrete_input_clear");
      UNITY_PRINT_EOL();
      UnityPrint("  test_discrete_input_out_of_bounds_returns_false");
      UNITY_PRINT_EOL();
      UnityPrint("  test_input_reg_set_and_get");
      UNITY_PRINT_EOL();
      UnityPrint("  test_input_reg_boundary_last");
      UNITY_PRINT_EOL();
      UnityPrint("  test_input_reg_out_of_bounds_returns_zero");
      UNITY_PRINT_EOL();
      UnityPrint("  test_get_data_store_not_null");
      UNITY_PRINT_EOL();
      UnityPrint("  test_get_data_store_reflects_set_reg");
      UNITY_PRINT_EOL();
      UnityPrint("  test_get_data_store_reflects_set_coil");
      UNITY_PRINT_EOL();
      UnityPrint("  test_fc03_holding_reg_read_via_accessor");
      UNITY_PRINT_EOL();
      UnityPrint("  test_fc06_write_single_reg_via_accessor");
      UNITY_PRINT_EOL();
      UnityPrint("  test_fc05_write_single_coil_via_accessor");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mb_poll_no_frame_no_crash");
      UNITY_PRINT_EOL();
      UnityPrint("  test_mb_enable_tx_rx_no_crash");
      UNITY_PRINT_EOL();
      return 0;
    }
    return parse_status;
  }
#endif
  UnityBegin("test_modbus_rtu.c");
  run_test(test_crc16_known_vector, "test_crc16_known_vector", 118);
  run_test(test_crc16_single_byte, "test_crc16_single_byte", 129);
  run_test(test_crc16_all_zeros, "test_crc16_all_zeros", 137);
  run_test(test_crc16_bit_flip_changes_crc, "test_crc16_bit_flip_changes_crc", 145);
  run_test(test_mb_float_roundtrip_50Hz, "test_mb_float_roundtrip_50Hz", 156);
  run_test(test_mb_float_roundtrip_negative, "test_mb_float_roundtrip_negative", 162);
  run_test(test_mb_float_roundtrip_zero, "test_mb_float_roundtrip_zero", 168);
  run_test(test_mb_float_roundtrip_large, "test_mb_float_roundtrip_large", 174);
  run_test(test_mb_float_uses_two_registers, "test_mb_float_uses_two_registers", 180);
  run_test(test_mb_float_big_endian_word_order, "test_mb_float_big_endian_word_order", 190);
  run_test(test_holding_reg_set_and_get, "test_holding_reg_set_and_get", 202);
  run_test(test_holding_reg_boundary_last, "test_holding_reg_boundary_last", 208);
  run_test(test_holding_reg_out_of_bounds_read_returns_zero, "test_holding_reg_out_of_bounds_read_returns_zero", 215);
  run_test(test_holding_reg_out_of_bounds_write_no_crash, "test_holding_reg_out_of_bounds_write_no_crash", 220);
  run_test(test_holding_reg_independent_addresses, "test_holding_reg_independent_addresses", 226);
  run_test(test_coil_set_true_get_true, "test_coil_set_true_get_true", 240);
  run_test(test_coil_set_false_get_false, "test_coil_set_false_get_false", 246);
  run_test(test_coil_adjacent_bits_independent, "test_coil_adjacent_bits_independent", 253);
  run_test(test_coil_boundary_last, "test_coil_boundary_last", 263);
  run_test(test_coil_out_of_bounds_read_returns_false, "test_coil_out_of_bounds_read_returns_false", 269);
  run_test(test_coil_byte_boundary, "test_coil_byte_boundary", 274);
  run_test(test_discrete_input_set_and_get, "test_discrete_input_set_and_get", 287);
  run_test(test_discrete_input_clear, "test_discrete_input_clear", 293);
  run_test(test_discrete_input_out_of_bounds_returns_false, "test_discrete_input_out_of_bounds_returns_false", 300);
  run_test(test_input_reg_set_and_get, "test_input_reg_set_and_get", 309);
  run_test(test_input_reg_boundary_last, "test_input_reg_boundary_last", 315);
  run_test(test_input_reg_out_of_bounds_returns_zero, "test_input_reg_out_of_bounds_returns_zero", 322);
  run_test(test_get_data_store_not_null, "test_get_data_store_not_null", 331);
  run_test(test_get_data_store_reflects_set_reg, "test_get_data_store_reflects_set_reg", 336);
  run_test(test_get_data_store_reflects_set_coil, "test_get_data_store_reflects_set_coil", 343);
  run_test(test_fc03_holding_reg_read_via_accessor, "test_fc03_holding_reg_read_via_accessor", 360);
  run_test(test_fc06_write_single_reg_via_accessor, "test_fc06_write_single_reg_via_accessor", 366);
  run_test(test_fc05_write_single_coil_via_accessor, "test_fc05_write_single_coil_via_accessor", 372);
  run_test(test_mb_poll_no_frame_no_crash, "test_mb_poll_no_frame_no_crash", 383);
  run_test(test_mb_enable_tx_rx_no_crash, "test_mb_enable_tx_rx_no_crash", 392);

  return UNITY_END();
}
