/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "unity.h"
#include "ram_pat_ck.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_ram_pat_ck_check_pattern_match(void);
extern void test_ram_pat_ck_check_pattern_mismatch(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
 int main(int argc, char** argv)
{
#ifdef UNITY_USE_COMMAND_LINE_ARGS
  int parse_status = UnityParseOptions(argc, argv);
  if (parse_status != 0)
  {
    if (parse_status < 0)
    {
      UnityPrint("test_ram_pat_ck.");
      UNITY_PRINT_EOL();
      UnityPrint("  test_ram_pat_ck_check_pattern_match");
      UNITY_PRINT_EOL();
      UnityPrint("  test_ram_pat_ck_check_pattern_mismatch");
      UNITY_PRINT_EOL();
      return 0;
    }
    return parse_status;
  }
#endif
  UnityBegin("test_ram_pat_ck.c");
  run_test(test_ram_pat_ck_check_pattern_match, "test_ram_pat_ck_check_pattern_match", 16);
  run_test(test_ram_pat_ck_check_pattern_mismatch, "test_ram_pat_ck_check_pattern_mismatch", 22);

  return UNITY_END();
}
