/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "unity.h"
#include "pll.h"
#include "arm_math.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_pll_init_1p_sets_theta_to_270(void);
extern void test_pll_init_1p_sets_delta_theta(void);
extern void test_pll_init_1p_stores_fs_and_f0(void);
extern void test_pll_init_1p_SOGI_cleared(void);
extern void test_pll_init_3p_sets_theta_to_270(void);
extern void test_pll_init_3p_sets_delta_theta(void);
extern void test_pll_is_locked_returns_0_before_lock(void);
extern void test_pll_is_locked_returns_1_when_counter_at_threshold(void);
extern void test_pll_is_locked_returns_0_when_counter_below_threshold(void);
extern void test_pll_update_1p_theta_stays_in_0_to_360(void);
extern void test_pll_update_3p_theta_stays_in_0_to_360(void);
extern void test_pll_update_1p_frequency_estimate_within_2Hz(void);
extern void test_pll_update_3p_frequency_estimate_within_2Hz(void);
extern void test_pll_update_1p_locks_within_max_cycles(void);
extern void test_pll_update_3p_locks_within_max_cycles(void);
extern void test_pll_update_1p_tracks_49Hz(void);
extern void test_pll_update_3p_tracks_51Hz(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
 int main(int argc, char** argv)
{
#ifdef UNITY_USE_COMMAND_LINE_ARGS
  int parse_status = UnityParseOptions(argc, argv);
  if (parse_status != 0)
  {
    if (parse_status < 0)
    {
      UnityPrint("test_pll.");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_init_1p_sets_theta_to_270");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_init_1p_sets_delta_theta");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_init_1p_stores_fs_and_f0");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_init_1p_SOGI_cleared");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_init_3p_sets_theta_to_270");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_init_3p_sets_delta_theta");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_is_locked_returns_0_before_lock");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_is_locked_returns_1_when_counter_at_threshold");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_is_locked_returns_0_when_counter_below_threshold");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_update_1p_theta_stays_in_0_to_360");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_update_3p_theta_stays_in_0_to_360");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_update_1p_frequency_estimate_within_2Hz");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_update_3p_frequency_estimate_within_2Hz");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_update_1p_locks_within_max_cycles");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_update_3p_locks_within_max_cycles");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_update_1p_tracks_49Hz");
      UNITY_PRINT_EOL();
      UnityPrint("  test_pll_update_3p_tracks_51Hz");
      UNITY_PRINT_EOL();
      return 0;
    }
    return parse_status;
  }
#endif
  UnityBegin("test_pll.c");
  run_test(test_pll_init_1p_sets_theta_to_270, "test_pll_init_1p_sets_theta_to_270", 67);
  run_test(test_pll_init_1p_sets_delta_theta, "test_pll_init_1p_sets_delta_theta", 75);
  run_test(test_pll_init_1p_stores_fs_and_f0, "test_pll_init_1p_stores_fs_and_f0", 84);
  run_test(test_pll_init_1p_SOGI_cleared, "test_pll_init_1p_SOGI_cleared", 92);
  run_test(test_pll_init_3p_sets_theta_to_270, "test_pll_init_3p_sets_theta_to_270", 101);
  run_test(test_pll_init_3p_sets_delta_theta, "test_pll_init_3p_sets_delta_theta", 109);
  run_test(test_pll_is_locked_returns_0_before_lock, "test_pll_is_locked_returns_0_before_lock", 121);
  run_test(test_pll_is_locked_returns_1_when_counter_at_threshold, "test_pll_is_locked_returns_1_when_counter_at_threshold", 129);
  run_test(test_pll_is_locked_returns_0_when_counter_below_threshold, "test_pll_is_locked_returns_0_when_counter_below_threshold", 137);
  run_test(test_pll_update_1p_theta_stays_in_0_to_360, "test_pll_update_1p_theta_stays_in_0_to_360", 149);
  run_test(test_pll_update_3p_theta_stays_in_0_to_360, "test_pll_update_3p_theta_stays_in_0_to_360", 164);
  run_test(test_pll_update_1p_frequency_estimate_within_2Hz, "test_pll_update_1p_frequency_estimate_within_2Hz", 183);
  run_test(test_pll_update_3p_frequency_estimate_within_2Hz, "test_pll_update_3p_frequency_estimate_within_2Hz", 197);
  run_test(test_pll_update_1p_locks_within_max_cycles, "test_pll_update_1p_locks_within_max_cycles", 216);
  run_test(test_pll_update_3p_locks_within_max_cycles, "test_pll_update_3p_locks_within_max_cycles", 230);
  run_test(test_pll_update_1p_tracks_49Hz, "test_pll_update_1p_tracks_49Hz", 250);
  run_test(test_pll_update_3p_tracks_51Hz, "test_pll_update_3p_tracks_51Hz", 265);

  return UNITY_END();
}
