#ifndef APP_CFG_H
#define APP_CFG_H

#define APP_DEFAULT_TASK_STACK_SIZE 256U
#define APP_DEFAULT_TASK_PRIORITY 1U
#define APP_DEFAULT_QUEUE_LENGTH 10U

#define DSP_USE_FLOAT 1u
#define USE_MOCK  1u

#define METER_PHASE_COUNT 3U
#define METER_MAIN_FREQUENCY 50U
#define METER_START_FREQUENCY 60U
#define METER_SAMPLES_PER_CYCLE 128U
#define METER_SIGNAL_COUNT 2u  // Voltage and current
#define METER_SAMPLES_RATE (METER_SAMPLES_PER_CYCLE * METER_MAIN_FREQUENCY)

#define DATA_USE_MOCK_DATA 1U


#define BIN_1_COUNT 8
#define FFT_BUF_SIZE (METER_SAMPLES_PER_CYCLE * BIN_1_COUNT)

/* deadline_monitor: max expected task iteration / work time (microseconds) */
#define DM_DEADLINE_ADC_SAMPLE_TASK_US 10000U
#define DM_DEADLINE_COMM_TASK_US 200000U
#define DM_DEADLINE_LED_BLINK_TASK_US 80000U
#define DM_DEADLINE_MOCK_SIGNAL_TASK_US 50000U
#define DM_DEADLINE_DEFAULT_TASK_US 10000U

#endif /* APP_CFG_H */