#ifndef APP_CFG_H
#define APP_CFG_H

#define APP_DEFAULT_TASK_STACK_SIZE 256U
#define APP_DEFAULT_TASK_PRIORITY 1U
#define APP_DEFAULT_QUEUE_LENGTH 10U

#define DSP_USE_FLOAT 1u
#define USE_MOCK  1u

#define METER_PHASE_COUNT 3U
#define METER_MAIN_FREQUENCY 50U
#define METER_START_FREQUENCY 60U
#define METER_SAMPLES_PER_CYCLE 128U
#define METER_SIGNAL_COUNT 2u  // Voltage and current
#define METER_SAMPLES_RATE (METER_SAMPLES_PER_CYCLE * METER_MAIN_FREQUENCY)

#define DATA_USE_MOCK_DATA 1U


#define BIN_1_COUNT 8
#define FFT_BUF_SIZE (METER_SAMPLES_PER_CYCLE * BIN_1_COUNT)

#endif /* APP_CFG_H */